version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - revive
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - style
        - diagnostic
        - performance
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
