#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$0")/../../../../.."

script/bindown -q install goreleaser
echo foo > "$ASSETS_DIR/foo.txt"
bin/goreleaser release --clean --skip-publish
cp dist/checksums.txt dist/release-train-test_*.tar.gz "$ASSETS_DIR"
nix run github:snowfallorg/nix-editor -- flake.nix outputs.packages.default.version -v "\"$RELEASE_TAG\"" -f -i
git add flake.nix
git commit -m "bump version to $RELEASE_TAG"
git tag "$RELEASE_TAG"
